# This is a CI workflow for running pytests

name: CI - Python

on:
  # Trigger the workflow on push or pull request but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
      - uses: actions/checkout@v2

      - name: Set up Python binary
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'

      - name: Display Python version
        run: echo "The Python version is $(which python)"

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Install Python dependencies
        run: poetry install

      - name: Run Pytest
        run : pytest tests -vvvv
