name: First interaction

on:
  pull_request:
  issues:

jobs:
  first-interaction:
    name: First interaction
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v1
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         issue-message: '#### Hi 👋\nThank you for opening your first issue in BGG-Companion!  Feel free to reach out to JDGiardino for pressing issues.'
         pr-message: '#### Hi 👋\nThank you for opening your first pull request in BGG-Companion! Be sure to checkout the [contributing guide](https://github.com/JDGiardino/BGG-Companion#readme)'
