name: DigitalOcean App Platform deployment
on:
  push:
    branches:
      - main
uses: digitalocean/app_action@main
with:
    app_name: bgg-companion
    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
