name: Lint

on:
  # Trigger the workflow on push or pull request but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x
          
      - name: Display Python version
        run: echo "The Python version is ${{ steps.save-python-version.outputs.PYTHON_VERSION }}"
        
      - name: Install Python dependencies
        run: pip install black

      - name : Run linter
        run: python -m black . --exclude gunicorn_config.py
        
      # I want to use this action for linters but it doesn't seem to have any "--exclude" functionality 
      #- name: Run linter
        #uses: wearerequired/lint-action@v2.0.0
        #with:
          #black : true
