---
name: Lint

on:  #  yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-linter:
    name: Python linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x

      - name: Display Python version
        run: echo "The Python version is $(which python)"

      - name: Install linter
        run: pip install black

      - name: Run linter
        run: python -m black . --check --diff

  run-yaml-linter:
    name: Yaml Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x

      - name: Install linter
        run: pip install --user yamllint

      - name: Setup yaml-lint
        run: yamllint .